# dclint disable service-image-require-explicit-tag
---
<<<<<<< HEAD
name: Secret Santa Project
services:
  secret-santa:
    image: jnstockley/secret-santa:latest
    # Update image to <DOCKER_USERNAME>/<REPO_NAME>
    container_name: secret-santa
=======
name: Python Starter Project
services:
  python-starter:
    image: jnstockley/python-starter:latest
    # Update image to <DOCKER_USERNAME>/<REPO_NAME>
    container_name: python-starter
>>>>>>> external/main
    env_file:
      - .env
    restart: unless-stopped
