# dclint disable service-image-require-explicit-tag
---
name: Secret Santa Project
services:
  secret-santa:
    image: jnstockley/secret-santa:latest
    # Update image to <DOCKER_USERNAME>/<REPO_NAME>
    container_name: secret-santa
    env_file:
      - .env
    restart: unless-stopped
